### PR TITLE
Added maybe_resume decorator to read_nowait

### PR DESCRIPTION
**Pull request by dalazx**
## Checklist
- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] Add yourself to `CONTRIBUTORS.txt`
- [ ] Add a new entry to `CHANGES.rst`
  - Choose any open position to avoid merge conflicts with other PRs.
  - Add a link to the issue you are fixing (if any) using `#isuue_number` format at the end of changelog message. Use Pull Request number if there are no issues for PR or PR covers the issue only partially.

### CODE REVIEW

**Comment by dalazx** [comment]
@jettify @bdrosen96 please take a look

**Comment by bdrosen96** [comment]
Looks good, but should there be a test case of some kind?

Do we want to try to get this into official repo rather than fork?

**Comment by dalazx** [comment]
Sure, I was going to add tests soon. 
Regarding the upstream repo, yes, we do want, but I'm afraid it can take some time to merge and release a new version, can't it.

**Comment by dalazx** [comment]
Added tests. Found a few minor bugs there.

**Comment by bdrosen96** [comment]
This basically looks good. However, I think that for 2.9 at least we want to use a release based off of 0.21.4 that we currently use now rather than latest master since we don't have enough time to test it to make sure it does not introduce new issues for 2.9.

**Comment by dalazx** [comment]
true. will rebase.

**Comment by dalazx** [comment]
Ok. I rebased onto the branch based on v0.21.4 tag. But issue is that there is basically nothing I can merge into. So for now we'll end up using this branch and also I'm gonna tag the most recent commit as `v0.21.4_fixed`

**Comment by bdrosen96** [comment]
Looks like a conflict here. Once that is resolved, this should be mergable then I guess we will need to do a release based on the fork off of the branch.

**Pull request merged**
